### ISSUE TITLE
[Bug]: Items pulled from slot 1 and slot 2 disappear

### ISSUE THREAD

**Issue by purejosh** [Fuzss/easyanvils#4]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

Putting an item into slot 1 and 2 (the input slots) works fine, but pulling the items back out causes them to disappear. There's also a random issue where trying to pull the slot 3 item can cause it to randomly disappear too, though this is less common.

**Comment by purejosh** [comment]
As this is a critical bug, I'm removing the mod from my server. If you need something tested, please let me know.

**Comment by purejosh** [comment]
Here's the config:
```
#The maximum amount of enchantment level allowed to be spent in an anvil. Everything above will be 'Too Expensive!' and will be disallowed.
#This option isn't that impactful anymore when prior work penalties are disabled; repair costs will basically never reach such a high value anymore.
#Range: > -2147483648
max_anvil_repair_cost = 40
#When combining enchanted items in an anvil, prevent an enchantment level higher than the max level value for that enchantment from being lowered to said max value.
no_anvil_max_level_limit = true
#Chance the anvil will break into chipped or damaged variant, or break completely after using. Value is set to 0.12 in vanilla.
#Range: 0.0 ~ 1.0
anvil_break_chance = 0.05
#Solely renaming items in an anvil will never cause the anvil to break.
risk_free_anvil_renaming = true
#Renaming name tags in an anvil no longer costs any enchantment levels at all.
free_name_tag_renames = true
#Repairing items in an anvil multiple times will not make subsequent repairs more and more expensive.
disable_prior_work_penalty = true
#Edit name tags without cost nor anvil, simply by sneak + right-clicking.
edit_name_tags_no_anvil = true
#The naming field in anvils and the name tag gui will support formatting codes for setting custom text colors and styles.
#Check out the Minecraft Wiki for all available formatting codes and their usage: https://minecraft.fandom.com/wiki/Formatting_codes#Usage
renaming_supports_formatting = true
#Allow using iron blocks to repair an anvil by one stage. Can be automated using dispensers.
anvil_repairing = true
```

**Comment by purejosh** [comment]
Mods list: 
```
Name
----
Adorn-3.6.1+1.19-fabric.jar
advancednetherite-fabric-1.6.4-1.19.2.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
advdebug-2.3.0.jar
adventurez-1.4.16.jar
AirHop-v4.2.1-1.19.2-Fabric.jar
AmbientSounds_FABRIC_v5.2.1_mc1.19.1.jar
appleskin-fabric-mc1.19-2.4.1.jar
appliedenergistics2-12.1.2-beta.jar
architects-palette-fabric-2.1.1.jar
architectury-6.2.43-fabric.jar
BarteringStation-v4.0.0-1.19.2-Fabric.jar
bclib-2.1.0.jar
better-end-2.1.0.jar
better-nether-7.1.0.jar
betteranimalsplus-1.19-11.0.7-fabric.jar
BetterAnimationsCollection-v4.0.1-1.19.2-Fabric.jar
BetterF3-1.3.2-Fabric-1.19.jar
betterfpsdist-fabric-1.19.1-1.9.jar
bettervillage_2_0_0.jar
biomemakeover-FABRIC-1.19.2-1.5.12.jar
blockus-2.5.2+1.19.2.jar
BOMD-1.4.2-1.19.jar
Bookshelf-Fabric-1.19.2-16.1.4.jar
cardinal-components-api-5.0.1.jar
cem-0.7.1.jar
chat_heads-0.7.1-fabric-1.19.1.jar
chime-1.3.0.jar
CITResewn-1.1.1+1.19.jar
cloth-api-4.0.65.jar
cloth-config-8.0.75-fabric.jar
collective-fabric-1.19.2-4.50.jar
comforts-fabric-6.0.0+1.19.2.jar
consistency_plus-fabric-0.5.1+1.19.2.jar
continuity-2.0.1+1.19.jar
CosmeticArmor-1.19-1.4.0.jar
CreativeCore_FABRIC_v2.7.4_mc1.19.1.jar
cullleaves-2.3.4.jar
customizableelytra-fabric-1.6.2-1.19.jar
Decorative+Blocks-fabric-1.19.2-3.0.0.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
dummmmmmy-FABRIC-1.19-1.5.3.jar
durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar
dynamic-fps-2.2.0.jar
earthtojavamobs-fabric-1.9.3+1.19.2.jar
EasyAnvils-v4.0.1-1.19.2-Fabric.jar
EasyMagic-v4.3.2-1.19.2-Fabric.jar
ecologics-fabric-1.19.2-2.1.9.jar
eden-ring-0.6.4.jar
effective-1.2.2.jar
eldritch-mobs-1.12.6.jar
ellemes-container-library-2.0.1+1.19-fabric.jar
elytraslot-fabric-6.0.0+1.19.2.jar
EmeraldTools-Fabric-1.19.2-1.4.29.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.3.jar
entityculling-fabric-1.5.2-mc1.19.jar
entity_texture_features_fabric_1.19.x-4.0.2.jar
expandeddelight-0.2.2.jar
expandedstorage-8.0.1+1.19-fabric.jar
fabric-api-0.60.0+1.19.2.jar
fabric-carpet-1.19.1-1.4.83+v220727.jar
fabric-end-remastered-5.1.1.jar
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar
FabricProxy-Lite-2.3.0.jar
fallingleaves-1.12.2+1.19.2.jar
farmers-delight-fabric-1.19.X-1.3.3.jar
farsight-fabric-1.19.1-2.0.jar
ferritecore-5.0.0-fabric.jar
ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
frame-fabric-0.26.0+1.19.jar
friendsandfoes-fabric-mc1.19.2-1.5.6.jar
FrogLegs-v1.0.0-1.19.2-Fabric.jar
geckolib-fabric-1.19-3.1.17.jar
goldensteak-1.0.5-1.19.jar
grind-enchantments-2.0.0-beta.2+1.19.2.jar
guard-villagers-fabric-1.19-1.0.16.jar
hexbattletower-1.0.jar
illuminations-1.10.8.jar
impaled-1.1.4.jar
indium-1.0.9+mc1.19.2.jar
inmis-2.7.0-1.19.jar
inventorytotem-fabric_1.19.2-2.0.jar
iris-mc1.19.2-1.2.8.jar
justmobheads-fabric_1.19.2-5.9.jar
justplayerheads-fabric_1.19.2-2.4.jar
konkrete_fabric_1.5.0_MC_1.19.1.jar
lambdynamiclights-2.1.2+1.19.jar
lazydfu-0.1.3.jar
libraryferret-fabric-1.19.2-3.0.0.jar
lithium-fabric-mc1.19.2-0.8.3.jar
lootr-1.19-0.4.22.61.jar
LuckPerms-Fabric-5.4.41.jar
malilib-fabric-1.19.2-0.13.0.jar
mavm-1.1.0-mc1.19.jar
mcda-2.2.0.jar
mcdw-5.0.3-1.19.jar
mcsa-2.4.0-1.19.jar
mcw-bridges-2.0.3fabric-mc1.19.jar
mcw-doors-1.0.7fabric-mc1.19.2.jar
mcw-fences-1.0.6fabric-mc1.19.2.jar
mcw-lights-1.0.4fabric-mc1.19.2.jar
mcw-paintings-1.0.4fabric-mc1.19.2.jar
mcw-paths-1.0.1fabric-mc1.19.2.jar
mcw-roofs-2.2.0-mc1.19.2-fabric.jar
mcw-trapdoors-1.0.7fabric-mc1.19.2.jar
mcw-windows-2.0.3bfabric-mc1.19.jar
megaparrot-1.0.5.jar
Mo-Glass-1.6.1-MC1.19.2.jar
mobscarecrow-2.2.1-1.19.1.jar
modmenu-4.0.6.jar
morefrogs-1.19.x-1.2.2-fabric.jar
music-box-v1.0.1+1.19.2.jar
mvs-2.5.8.jar
naturalist-fabric-2.1.1-1.19.2.jar
NaturesCompass-1.19.2-2.0.4-fabric.jar
NoChatReports-FABRIC-1.19.2-v1.12.0.jar
nofade-1.18-2.0.1.jar
NoFog-1.3.1_1.16.5-1.19.2-fabric.jar
notenoughanimations-fabric-1.6.1-mc1.19.1.jar
notenoughcrashes-4.1.8+1.19.2-fabric.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.10.jar
open-parties-and-claims-fabric-1.19.2-0.14.1.jar
ostOverhaul-0.2.6-1.19.1.jar
Patchouli-1.19.2-76-FABRIC.jar
Pehkui-3.4.1+1.14.4-1.19.2.jar
PickUpNotifier-v4.2.0-1.19.2-Fabric.jar
polymorph-fabric-0.45.0+1.19.2.jar
probablychests-0.5.4-1.19.1.jar
PuzzlesLib-v4.3.9-1.19.2-Fabric.jar
redstructure-1.0.4-fabric-1.19.2.jar
RoughlyEnoughItems-9.1.530.jar
shulkerboxtooltip-fabric-3.1.2+1.19.2.jar
skylorlib-1.5.1.jar
SkyVillages-1.0.2.1-1.19.x-fabric.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
sprout-1.4.2-fabric.jar
starlight-1.1.1+fabric.ae22326 (1).jar
stoneholm-1.4.4.jar
styled-chat-1.4.1+1.19.2.jar
StylishEffects-v4.3.0-1.19.2-Fabric.jar
SweetBerryFoods-v2.1.0-1.19.2-Fabric.jar
tabtps-fabric_1_3_15.jar
TaxFreeLevels-1.3.3-fabric-1.19.jar
TerraBlender-fabric-1.19.2-2.0.1.125.jar
time-and-wind-ct-1.4.3+1.19.2.jar
TinySkeletons-v4.2.0-1.19.2-Fabric.jar
tooltipfix-1.0.5-1.19.jar
torohealth-1.19-fabric-1.jar
TradingPost-v4.2.0-1.19.2-Fabric.jar
transportables-1.2.1.jar
trinkets-3.4.0.jar
twigs-2.0.0-beta.9+1.19-fabric.jar
ultris-v5.6.4d-fabric-1.19.jar
VanillaTweaks-fabric-1.19-1.5.61.jar
VisualWorkbench-v4.2.0-1.19.2-Fabric.jar
voicechat-fabric-1.19.2-2.3.7.jar
voidz-1.0.9.jar
WI-Zoom-1.4-MC1.19.2.jar
WilderWild-1.0.6-Fabric+1.19.2.jar
wraith-waystones-3.0.3+mc1.19.2.jar
wwoo-3.1.7+FABRIC+1.19.2.jar
XaerosWorldMap_1.27.0_Fabric_1.19.1.jar
Xaeros_Minimap_22.14.1_Fabric_1.19.1.jar
xlpackets-2.1-1.17.1.jar
xp_obelisk-0.4.5.r_for_1.19.x_Fabric.jar
youre-in-grave-danger-1.4.2.jar
```

**Comment by purejosh** [comment]
https://user-images.githubusercontent.com/70633949/194998781-55df78cf-45de-421e-96e1-9f46f9cf7cc6.mp4

**Comment by purejosh** [comment]
I know it has only been 5 days, but has there been any progress on this? Is there any way I can help? If you want the modpack I'm using for this, I would happily export it for you. 

I mostly want the no work cost increases, that's such a helpful feature. :)

**Comment by Fuzss** [comment]
For that you can maybe use this mod in the meantime? https://www.curseforge.com/minecraft/mc-mods/no-enchant-cap

I'm really having a hard time reproducing this issue. A tried around a lot in our Better MC Fabric pack, but all worked as it should.

The thing is, the system implemented is designed for applying those tiny changes I make only when necessary to not mess too much with other mods. That makes it overly complicated for what it does, so there's definitely some room for error in there. Maybe I'll abandon that all together and just completely overwrite the anvil mechanics...

**Comment by purejosh** [comment]
Thanks for the reply. I'm wondering if there's anything special about my setup that's causing such a result. Are there any that maybe catch your eye, that you'd like for me to try testing without? This could totally be an incompat, but I'm clueless as to what.

**Comment by purejosh** [comment]
Using the mod you've recommended crashes the client when clicking on the enchantment table, which I have your Easy Magic mod installed. 
[crash-2022-10-16_22.11.42-client.txt](https://github.com/Fuzss/easyanvils/files/9796847/crash-2022-10-16_22.11.42-client.txt)

**Comment by Fuzss** [comment]
Should be fixed in v4.0.3! Can you confirm that?

**Comment by Hellession** [comment]
We are facing a near identical issue, though our configuration is different.
* We are running the Fabric Better MC modpack 1.19.2.
* Atop of those mods, we also run Ledger (grief protection) and dynmap-fabric.
* The issue ONLY takes place on our server, it does not occur in singleplayer.
* In v7.5 of the Modpack, the issue first started - the the errors in the logs were different from now.
* In v8 of the Modpack, the logs were spammed with a bunch of Exceptions referencing something from the Ledger mod.

Thus, I believe Ledger and EasyAnvils have some sort of incompatibility. I created a Minecraft server running Ledger and EasyAnvils and successfully reproduced the bug.
v4.0.3 did not fix it, though it seems as though the mod is currently being updated to v4.0.4?
I can share various logs in a sec

**Comment by Fuzss** [comment]
Should finally be fixed in v4.0.5, see the other issue report linked above.

**Comment by purejosh** [comment]
Thanks so much!

**Comment by purejosh** [comment]
I've had another occurrence. It has been fine for a few days now, and all of the sudden, I'm missing a netherite sword and an enchanted book. Sorry to say, I believe this isn't fixed yet.

**Comment by Fuzss** [comment]
Did you leave them on the anvil or did they vanish when moving the items in the screen?

**Comment by purejosh** [comment]
I believe I left it on the anvil.

**Comment by Fuzss** [comment]
The fix for #23 should resolve this, too.
