### ISSUE TITLE
[Bug]: Anvil says break and replace but then when i do it nothing happens

### ISSUE THREAD

**Issue by Eyorie** [Fuzss/easyanvils#47]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

I just downloaded easy anvils and it tells me to break and replace the anvil block but it still doesn't work 

I added the mod later in our playthrough as it has just been updated to 1.20.4 the version we are playing on

![Base Profile Screenshot 2024 01 25 - 01 42 20 43](https://github.com/Fuzss/easyanvils/assets/157683263/e633b83f-fff2-4c7c-b7bd-62541d13560b)

### latest.log (Required)

https://gist.github.com/Eyorie/0cf2f63dd5de34aaedff218b6f507dbd

**Comment by ZerJ704** [comment]
i have the same problem for this

**Comment by gvancamp** [comment]
The same exact thing happens with the enchanting table with Easy Magic as well.

**Comment by ZerJ704** [comment]
> The same exact thing happens with the enchanting table with Easy Magic as well.

I don't think so, easy magic work for me after I break and replace it

**Comment by Fuzss** [comment]
Fixed in v20.4.9 of Puzzles Lib.

**Comment by danish-fareed** [comment]
Hi i am still getting this problem in Fabric 1.21 Any solution>?
